include(adafruit-feather-m0-basic)

# ignored in Git, just your local tweaks and paths
include(config.local.cmake OPTIONAL)

if(NOT DEFINED SERIAL_DEV)
	if(DEFINED ENV{SERIAL_DEV})
		set(SERIAL_DEV "$ENV{SERIAL_DEV}" CACHE STRING "Target serial port device")
	else()
		set(SERIAL_DEV "/dev/ttyACM0" CACHE STRING "Target serial port device")
	endif()
endif()

# We need to set variables bellow before setting CMAKE_PREFIX_PATH which needs
# to be set before we set CMAKE_TOOLCHAIN_FILE
if (NOT DEFINED ADAFRUIT_SAMD_VERSION)
	set(ADAFRUIT_SAMD_VERSION 1.0.19)
endif()

if (NOT DEFINED ARDUINO_BOSSAC_VERSION)
	set(ARDUINO_BOSSAC_VERSION 1.7.0)
endif()

if (NOT DEFINED ARDUINO_TOOLCHAIN_VERSION)
	set(ARDUINO_TOOLCHAIN_VERSION 4.8.3-2014q1)
endif()

if (NOT DEFINED ARDUINO_CMSIS_VERSION)
	set(ARDUINO_CMSIS_VERSION 4.5.0)
endif()

if (NOT DEFINED ARDUINO_CMSIS_ATMEL_VERSION)
	set(ARDUINO_CMSIS_ATMEL_VERSION 1.1.0)
endif()

if(DEFINED ENV{ARDUINO_PACKAGES_PATH})
	set(ARDUINO_PACKAGES_PATH "$ENV{ARDUINO_PACKAGES_PATH}" CACHE PATH "Arduino packages path")
endif()

if(NOT DEFINED ARDUINO_PACKAGES_PATH)
	message(FATAL_ERROR "Please set ARDUINO_PACKAGES_PATH environment or CMake variable")
endif()

if (NOT DEFINED ARDUINO_TOOLS_PATH)
	set(ARDUINO_TOOLS_PATH "${ARDUINO_PACKAGES_PATH}/arduino/tools")
endif()

if (NOT DEFINED ADAFRUIT_SAMD_PATH)
	set(ADAFRUIT_SAMD_PATH "${ARDUINO_PACKAGES_PATH}/adafruit/hardware/samd/${ADAFRUIT_SAMD_VERSION}")
endif()

if (NOT DEFINED ARDUINO_CMSIS_PATH)
	set(ARDUINO_CMSIS_PATH "${ARDUINO_TOOLS_PATH}/CMSIS/${ARDUINO_CMSIS_VERSION}")
endif()

if (NOT DEFINED ARDUINO_BOSSAC_PATH)
	set(ARDUINO_BOSSAC_PATH "${ARDUINO_TOOLS_PATH}/bossac/${ARDUINO_BOSSAC_VERSION}")
endif()

if (NOT DEFINED ARDUINO_CMSIS_INCLUDE_PATH)
	set(ARDUINO_CMSIS_INCLUDE_PATH "${ARDUINO_CMSIS_PATH}/CMSIS/Include")
endif()

if (NOT DEFINED ARDUINO_CMSIS_LIB_PATH)
	set(ARDUINO_CMSIS_LIB_PATH "${ARDUINO_CMSIS_PATH}/CMSIS/Lib/GCC")
endif()

if (NOT DEFINED ARDUINO_CMSIS_ATMEL_PATH)
	set(ARDUINO_CMSIS_ATMEL_PATH "${ARDUINO_TOOLS_PATH}/CMSIS-Atmel/${ARDUINO_CMSIS_ATMEL_VERSION}")
endif()

if (NOT DEFINED ARDUINO_CMSIS_ATMEL_INCLUDE_PATH)
	set(ARDUINO_CMSIS_ATMEL_INCLUDE_PATH "${ARDUINO_CMSIS_ATMEL_PATH}/CMSIS/Device/ATMEL")
endif()

if (NOT DEFINED ARDUINO_TOOLCHAIN_PATH)
	set(ARDUINO_TOOLCHAIN_PATH "${ARDUINO_TOOLS_PATH}/arm-none-eabi-gcc/${ARDUINO_TOOLCHAIN_VERSION}")
endif()

set(CMAKE_PREFIX_PATH "${ARDUINO_TOOLCHAIN_PATH}")

# show a list of libs linked
# set(EXTRA_LINKER_FLAGS "-Wl,--trace")

set(CMAKE_TOOLCHAIN_FILE cmake/samd-arduino-toolchain.cmake)
