include(cortex-m0-plus)

set(F_CPU 48000000)
set(USB_VID 0x239A)
set(USB_PID 0x800B)
set(USB_MANUFACTURER Adafruit)
set(USB_PRODUCT "Feather M0")
set(TARGET_BOARD ARDUINO_SAMD_FEATHER_M0)
set(BOARD_VARIANT arduino_zero)

add_definitions(
	-DMCU=${MCU} -DF_CPU=${F_CPU}L -DUSB_VID=${USB_VID}
	-DUSB_PID=${USB_PID} '-DUSB_MANUFACTURER="${USB_MANUFACTURER}"'
	'-DUSB_PRODUCT="${USB_PRODUCT}"' -D${TARGET_BOARD}
	-DARDUINO_ARCH_SAMD -DARDUINO_SAMD_ZERO -D__SAMD21G18A__ -DUSBCON
)
